version: '3.4'

services:
    vdb.ui:
        container_name: vdb.ui
        image: vdbdocker/vdb:vdbui
        build:
            context: .
            dockerfile: .dockerfile        
        ports:
            - "8080:8080"